### ISSUE TITLE
Server Issue(s)

### ISSUE THREAD

**Issue by DairyStix** [cseagle/collabREate#4]
Hi Chris,

I've just built the server following the requirements outlined in your readme. Im running a windows 10 machine x64 and using IDA 7.1. 

1) Currently I'm getting : "Server is in basic mode, updates are not stored","type":"collab_error" - after connecting to my server successfully.

2) After connecting and accessing the collabreate plugin menu with the options "Set checkpoint" "fork project" etc. there is no "Ok" or "cancel" button so I am unable to select any of the options.

Not sure if I'm missing something but any help would be great.

Many thanks.

**Comment by cseagle** [comment]
Thanks for the feedback. The first message is not really an error per se, more of a limitation. This has been lifted on the testing branch which now caches all updates in memory on the server when in basic mode (I assume you were not in DB mode, otherwise this would truly be an error)

The second problem is also fixed in the testing branch.

**Comment by DairyStix** [comment]
Hi Chris,

Thanks for the reply!

I have followed your instructions when setting the server up but I'm still getting "Server is in basic mode". How do I change it to database mode?

Many thanks.

**Comment by cseagle** [comment]
Merged testing into master
